config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :marketing_contents
  resources :communication_designs
  resources :human_resources
  resources :event_operations
  resources :sponsor_levels
  resources :sponsors
  resources :marketings
  resources :speakers
  resources :speaking_topics
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/human_resource.rb
class HumanResource < ApplicationRecord
	validates_presence_of :Member_Name, :Contact_Number, :Email, :Department, :Position
end

app/controllers/human_resources_controller.rb
class HumanResourcesController < ApplicationController
  before_action :set_human_resource, only: %i[ show edit update destroy ]

  # GET /human_resources or /human_resources.json
  def index
    @human_resources = HumanResource.all
  end

  # GET /human_resources/1 or /human_resources/1.json
  def show
  end

  # GET /human_resources/new
  def new
    @human_resource = HumanResource.new
  end

  # GET /human_resources/1/edit
  def edit
  end

  # POST /human_resources or /human_resources.json
  def create
    @human_resource = HumanResource.new(human_resource_params)

    respond_to do |format|
      if @human_resource.save
        format.html { redirect_to human_resource_url(@human_resource), notice: "Human resource was successfully created." }
        format.json { render :show, status: :created, location: @human_resource }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @human_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /human_resources/1 or /human_resources/1.json
  def update
    respond_to do |format|
      if @human_resource.update(human_resource_params)
        format.html { redirect_to human_resource_url(@human_resource), notice: "Human resource was successfully updated." }
        format.json { render :show, status: :ok, location: @human_resource }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @human_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /human_resources/1 or /human_resources/1.json
  def destroy
    @human_resource.destroy

    respond_to do |format|
      format.html { redirect_to human_resources_url, notice: "Human resource was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_human_resource
      @human_resource = HumanResource.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def human_resource_params
      params.require(:human_resource).permit(:Member_ID, :Member_Name, :Contact_Number, :Email, :Department, :Description, :Position, :Bio)
    end
end

app/helpers/human_resources_helper.rb
module HumanResourcesHelper
end

app/views/human_resources/_form.html.erb
<%= form_with(model: human_resource) do |form| %>
<% if human_resource.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(human_resource.errors.count, "error") %> prohibited this human_resource from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% human_resource.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :Member_ID, class: label_class %>
          <%= form.number_field :Member_ID, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Member_Name, class: label_class %>
          <%= form.text_area :Member_Name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Contact_Number, class: label_class %>
          <%= form.number_field :Contact_Number, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Email, class: label_class %>
          <%= form.text_area :Email, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Department, class: label_class %>
          <%= form.text_area :Department, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Description, class: label_class %>
          <%= form.text_area :Description, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Position, class: label_class %>
          <%= form.text_area :Position, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Bio, class: label_class %>
          <%= form.text_area :Bio, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if human_resource.persisted? %>
<%= link_to "Cancel", human_resource, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", human_resources_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/human_resources/_human_resource.html.erb
<div id="<%= dom_id human_resource %>">
  <p>
    <strong>Member id:</strong>
    <%= human_resource.Member_ID %>
  </p>

  <p>
    <strong>Member name:</strong>
    <%= human_resource.Member_Name %>
  </p>

  <p>
    <strong>Contact number:</strong>
    <%= human_resource.Contact_Number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= human_resource.Email %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= human_resource.Department %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= human_resource.Description %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= human_resource.Position %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= human_resource.Bio %>
  </p>

</div>

app/views/human_resources/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit human_resource</h1>
    <% if @human_resource.persisted? %>
    <%= button_to 'Destroy', @human_resource, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', human_resource: @human_resource %>
</div>

app/views/human_resources/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Human_resources</h1>

    <%= link_to new_human_resource_path, class: button_class(theme: "primary") do %>
    Add New Human resource
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Member id</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Member name</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Contact number</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Email</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Department</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Description</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Position</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Bio</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @human_resources.each do |human_resource| %>
      <%= content_tag :tr, id: dom_id(human_resource), class: dom_class(human_resource) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= human_resource.Member_ID %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= human_resource.Member_Name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= human_resource.Contact_Number %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= human_resource.Email %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= human_resource.Department %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= human_resource.Description %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= human_resource.Position %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= human_resource.Bio %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', human_resource %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/human_resources/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New human_resource</h1>

  <%= render 'form', human_resource: @human_resource %>
</div>

app/views/human_resources/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Human_resource</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to human_resources_path, class: button_class(theme: "transparent") do %>
      All Human_resources
      <% end %>
      <%= link_to edit_human_resource_path(@human_resource), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Member id:</p>
        <p><%= @human_resource.Member_ID %></p>
      </li>
      <li>
        <p class="font-semibold">Member name:</p>
        <p><%= @human_resource.Member_Name %></p>
      </li>
      <li>
        <p class="font-semibold">Contact number:</p>
        <p><%= @human_resource.Contact_Number %></p>
      </li>
      <li>
        <p class="font-semibold">Email:</p>
        <p><%= @human_resource.Email %></p>
      </li>
      <li>
        <p class="font-semibold">Department:</p>
        <p><%= @human_resource.Department %></p>
      </li>
      <li>
        <p class="font-semibold">Description:</p>
        <p><%= @human_resource.Description %></p>
      </li>
      <li>
        <p class="font-semibold">Position:</p>
        <p><%= @human_resource.Position %></p>
      </li>
      <li>
        <p class="font-semibold">Bio:</p>
        <p><%= @human_resource.Bio %></p>
      </li>
  </ul>
</div>