config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :marketing_contents
  resources :communication_designs
  resources :human_resources
  resources :event_operations
  resources :sponsor_levels
  resources :sponsors
  resources :marketings
  resources :speakers
  resources :speaking_topics
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/communication_design.rb
class CommunicationDesign < ApplicationRecord
  has_one_attached :File
  validates_presence_of :Task_Name, :Description, :File, :Deadline, :Person_in_Charge
end

app/controllers/communication_designs_controller.rb
class CommunicationDesignsController < ApplicationController
  before_action :set_communication_design, only: %i[ show edit update destroy ]

  # GET /communication_designs or /communication_designs.json
  def index
    @communication_designs = CommunicationDesign.all
  end

  # GET /communication_designs/1 or /communication_designs/1.json
  def show
  end

  # GET /communication_designs/new
  def new
    @communication_design = CommunicationDesign.new
  end

  # GET /communication_designs/1/edit
  def edit
  end

  # POST /communication_designs or /communication_designs.json
  def create
    @communication_design = CommunicationDesign.new(communication_design_params)

    respond_to do |format|
      if @communication_design.save
        format.html { redirect_to communication_design_url(@communication_design), notice: "Communication design was successfully created." }
        format.json { render :show, status: :created, location: @communication_design }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @communication_design.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communication_designs/1 or /communication_designs/1.json
  def update
    respond_to do |format|
      if @communication_design.update(communication_design_params)
        format.html { redirect_to communication_design_url(@communication_design), notice: "Communication design was successfully updated." }
        format.json { render :show, status: :ok, location: @communication_design }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @communication_design.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communication_designs/1 or /communication_designs/1.json
  def destroy
    @communication_design.destroy

    respond_to do |format|
      format.html { redirect_to communication_designs_url, notice: "Communication design was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_communication_design
      @communication_design = CommunicationDesign.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def communication_design_params
      params.require(:communication_design).permit(:Marcom_ID, :Task_Name, :Description, :File, :Deadline, :Person_in_Charge, :Note)
    end
end

app/helpers/communication_designs_helper.rb
module CommunicationDesignsHelper
end

app/views/communication_designs/_communication_design.html.erb
<div id="<%= dom_id communication_design %>">
  <p>
    <strong>Marcom id:</strong>
    <%= communication_design.Marcom_ID %>
  </p>

  <p>
    <strong>Task name:</strong>
    <%= communication_design.Task_Name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= communication_design.Description %>
  </p>

  <p>
    <strong>File:</strong>
    <%= link_to communication_design.File.filename, communication_design.File if communication_design.File.attached? %>
  </p>

  <p>
    <strong>Deadline:</strong>
    <%= communication_design.Deadline %>
  </p>

  <p>
    <strong>Person in charge:</strong>
    <%= communication_design.Person_in_Charge %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= communication_design.Note %>
  </p>

</div>

app/views/communication_designs/_form.html.erb
<%= form_with(model: communication_design) do |form| %>
<% if communication_design.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(communication_design.errors.count, "error") %> prohibited this communication_design from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% communication_design.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :Marcom_ID, class: label_class %>
          <%= form.number_field :Marcom_ID, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Task_Name, class: label_class %>
          <%= form.text_area :Task_Name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Description, class: label_class %>
          <%= form.text_area :Description, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :File, class: label_class %>
          <%= form.file_field :File, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Person_in_Charge, class: label_class %>
          <%= form.text_area :Person_in_Charge, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Note, class: label_class %>
          <%= form.text_area :Note, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if communication_design.persisted? %>
<%= link_to "Cancel", communication_design, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", communication_designs_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/communication_designs/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit communication_design</h1>
    <% if @communication_design.persisted? %>
    <%= button_to 'Destroy', @communication_design, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', communication_design: @communication_design %>
</div>

app/views/communication_designs/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Communication_designs</h1>

    <%= link_to new_communication_design_path, class: button_class(theme: "primary") do %>
    Add New Communication design
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Marcom id</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Task name</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Description</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">File</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Deadline</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Person in charge</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Note</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @communication_designs.each do |communication_design| %>
      <%= content_tag :tr, id: dom_id(communication_design), class: dom_class(communication_design) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= communication_design.Marcom_ID %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= communication_design.Task_Name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= communication_design.Description %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= communication_design.File %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= communication_design.Deadline %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= communication_design.Person_in_Charge %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= communication_design.Note %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', communication_design %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/communication_designs/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New communication_design</h1>

  <%= render 'form', communication_design: @communication_design %>
</div>

app/views/communication_designs/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Communication_design</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to communication_designs_path, class: button_class(theme: "transparent") do %>
      All Communication_designs
      <% end %>
      <%= link_to edit_communication_design_path(@communication_design), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Marcom id:</p>
        <p><%= @communication_design.Marcom_ID %></p>
      </li>
      <li>
        <p class="font-semibold">Task name:</p>
        <p><%= @communication_design.Task_Name %></p>
      </li>
      <li>
        <p class="font-semibold">Description:</p>
        <p><%= @communication_design.Description %></p>
      </li>
      <li>
        <p class="font-semibold">File:</p>
        <p><%= @communication_design.File %></p>
      </li>
      <li>
        <p class="font-semibold">Deadline:</p>
        <p><%= @communication_design.Deadline %></p>
      </li>
      <li>
        <p class="font-semibold">Person in charge:</p>
        <p><%= @communication_design.Person_in_Charge %></p>
      </li>
      <li>
        <p class="font-semibold">Note:</p>
        <p><%= @communication_design.Note %></p>
      </li>
  </ul>
</div>