config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :marketing_contents
  resources :communication_designs
  resources :human_resources
  resources :event_operations
  resources :sponsor_levels
  resources :sponsors
  resources :marketings
  resources :speakers
  resources :speaking_topics
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/event_operation.rb
class EventOperation < ApplicationRecord
	validates_presence_of :Task_Name, :Person_in_Charge, :Description, :Deadline, :Status
end

app/controllers/event_operations_controller.rb
class EventOperationsController < ApplicationController
  before_action :set_event_operation, only: %i[ show edit update destroy ]

  # GET /event_operations or /event_operations.json
  def index
    @event_operations = EventOperation.all
  end

  # GET /event_operations/1 or /event_operations/1.json
  def show
  end

  # GET /event_operations/new
  def new
    @event_operation = EventOperation.new
  end

  # GET /event_operations/1/edit
  def edit
  end

  # POST /event_operations or /event_operations.json
  def create
    @event_operation = EventOperation.new(event_operation_params)

    respond_to do |format|
      if @event_operation.save
        format.html { redirect_to event_operation_url(@event_operation), notice: "Event operation was successfully created." }
        format.json { render :show, status: :created, location: @event_operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event_operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_operations/1 or /event_operations/1.json
  def update
    respond_to do |format|
      if @event_operation.update(event_operation_params)
        format.html { redirect_to event_operation_url(@event_operation), notice: "Event operation was successfully updated." }
        format.json { render :show, status: :ok, location: @event_operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event_operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_operations/1 or /event_operations/1.json
  def destroy
    @event_operation.destroy

    respond_to do |format|
      format.html { redirect_to event_operations_url, notice: "Event operation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_operation
      @event_operation = EventOperation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_operation_params
      params.require(:event_operation).permit(:Task_ID, :Task_Name, :Person_in_Charge, :Description, :Deadline, :Status, :Note)
    end
end

app/helpers/event_operations_helper.rb
module EventOperationsHelper
end

app/views/event_operations/_event_operation.html.erb
<div id="<%= dom_id event_operation %>">
  <p>
    <strong>Task id:</strong>
    <%= event_operation.Task_ID %>
  </p>

  <p>
    <strong>Task name:</strong>
    <%= event_operation.Task_Name %>
  </p>

  <p>
    <strong>Person in charge:</strong>
    <%= event_operation.Person_in_Charge %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event_operation.Description %>
  </p>

  <p>
    <strong>Deadline:</strong>
    <%= event_operation.Deadline %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= event_operation.Status %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= event_operation.Note %>
  </p>

</div>

app/views/event_operations/_form.html.erb
<%= form_with(model: event_operation) do |form| %>
<% if event_operation.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(event_operation.errors.count, "error") %> prohibited this event_operation from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% event_operation.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :Task_ID, class: label_class %>
          <%= form.number_field :Task_ID, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Task_Name, class: label_class %>
          <%= form.text_area :Task_Name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Person_in_Charge, class: label_class %>
          <%= form.text_area :Person_in_Charge, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Description, class: label_class %>
          <%= form.text_area :Description, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Deadline, class: label_class %>
          <%= form.datetime_field :Deadline, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Status, class: label_class %>
          <%= form.text_area :Status, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Note, class: label_class %>
          <%= form.text_area :Note, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if event_operation.persisted? %>
<%= link_to "Cancel", event_operation, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", event_operations_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/event_operations/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit event_operation</h1>
    <% if @event_operation.persisted? %>
    <%= button_to 'Destroy', @event_operation, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', event_operation: @event_operation %>
</div>

app/views/event_operations/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Event_operations</h1>

    <%= link_to new_event_operation_path, class: button_class(theme: "primary") do %>
    Add New Event operation
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Task id</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Task name</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Person in charge</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Description</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Deadline</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Status</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Note</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @event_operations.each do |event_operation| %>
      <%= content_tag :tr, id: dom_id(event_operation), class: dom_class(event_operation) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= event_operation.Task_ID %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= event_operation.Task_Name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= event_operation.Person_in_Charge %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= event_operation.Description %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= event_operation.Deadline %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= event_operation.Status %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= event_operation.Note %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', event_operation %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/event_operations/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New event_operation</h1>

  <%= render 'form', event_operation: @event_operation %>
</div>

app/views/event_operations/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Event_operation</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to event_operations_path, class: button_class(theme: "transparent") do %>
      All Event_operations
      <% end %>
      <%= link_to edit_event_operation_path(@event_operation), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Task id:</p>
        <p><%= @event_operation.Task_ID %></p>
      </li>
      <li>
        <p class="font-semibold">Task name:</p>
        <p><%= @event_operation.Task_Name %></p>
      </li>
      <li>
        <p class="font-semibold">Person in charge:</p>
        <p><%= @event_operation.Person_in_Charge %></p>
      </li>
      <li>
        <p class="font-semibold">Description:</p>
        <p><%= @event_operation.Description %></p>
      </li>
      <li>
        <p class="font-semibold">Deadline:</p>
        <p><%= @event_operation.Deadline %></p>
      </li>
      <li>
        <p class="font-semibold">Status:</p>
        <p><%= @event_operation.Status %></p>
      </li>
      <li>
        <p class="font-semibold">Note:</p>
        <p><%= @event_operation.Note %></p>
      </li>
  </ul>
</div>