config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :marketing_contents
  resources :communication_designs
  resources :human_resources
  resources :event_operations
  resources :sponsor_levels
  resources :sponsors
  resources :marketings
  resources :speakers
  resources :speaking_topics
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/communication_design.rb
class CommunicationDesign < ApplicationRecord
  has_one_attached :File
  validates_presence_of :Task_Name, :Description, :File, :Deadline, :Person_in_Charge
end

app/models/event_operation.rb
class EventOperation < ApplicationRecord
	validates_presence_of :Task_Name, :Person_in_Charge, :Description, :Deadline, :Status
end

app/models/human_resource.rb
class HumanResource < ApplicationRecord
	validates_presence_of :Member_Name, :Contact_Number, :Email, :Department, :Position
end

app/models/marketing_content.rb
class MarketingContent < ApplicationRecord
  has_one_attached :File
  validates_presence_of :Content_Name, :Description, :File, :Social_Networking_Platform, :Deadline, :Person_in_Charge
end

app/models/product.rb
class Product < ApplicationRecord
	validates_presence_of :name_of_product, :date, :origin, :packaging_measure, :supplier, :quantity
	validates_uniqueness_of :name_of_product
	validates_numericality_of :quantity

	validate :year_up_to_present
	def year_up_to_present
		errors.add(:field_name, 'Year must not be in the future') if date >
		Time.now.year
	end
end

app/models/speaker.rb
class Speaker < ApplicationRecord
  has_one_attached :Image_File
  validates_presence_of :Speaker_Name, :Topic_Name, :Bio, :Contact_Number, :Email, :Personal_ID, :Image_File, :Social_Media_Link, :Person_in_Charge
  validates_uniqueness_of :Speaker_Name, :Topic_Name, :Personal_ID
  validates_length_of :Contact_Number, maximum: 10
  validates_format_of :Email, with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validate :DOB
def DOB
errors.add(:field_name, 'Date of Birth must not be in the future') if year >
Time.now.year end
  validates_format_of :Social_Media_Link, with: URI::DEFAULT_PARSER.make_regexp(%w[http https])
end

app/models/speaking_topic.rb
class SpeakingTopic < ApplicationRecord
  has_one_attached :Image_File
  validates_presence_of :Topic_Name, :Description, :Image_File, :Video_Url, :Workspace_Link
  validates_uniqueness_of :Topic_Name
  validates_format_of :Workspace_Link, with: URI::DEFAULT_PARSER.make_regexp(%w[http https])
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  belongs_to :Sponsor_Level
  has_one_attached :Image_File
  has_one_attached :Contract_File
  validates_presence_of :Sponsor_Name, :Contact_Number, :Email, :Address, :Sponsor_Type, :Sponsorship_Level, :Contract_File, :Person_in_Charge, :Website_Link
  validates_uniqueness_of :Sponsor_Name
  validates_length_of :Contact_Number, maximum: 10
  validates_format_of :Email, with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates_format_of :Website_Link, with: URI::DEFAULT_PARSER.make_regexp(%w[http https])
end

app/models/sponsor_level.rb
class SponsorLevel < ApplicationRecord
	has_many :Sponsors
	validates_presence_of :Level_Name, :Value, :Description
	validates :Value, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name_of_product, :date, :origin, :packaging_measure, :supplier, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_classes(flash_type)
    flash_base = "px-2 py-4 mx-auto font-sans font-medium text-center text-white"
    {
      notice: "bg-indigo-600 #{flash_base}",
      error:  "bg-red-600 #{flash_base}",
      alert: "bg-red-600 #{flash_base}"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def nav_classes
    ["devise/registrations", "devise/sessions", "devise/confirmations", "devise/passwords", "devise/unlocks"].include?(params[:controller]) ? "hidden" : nil
  end

  def label_class(options={})
    "block mb-1 font-normal leading-normal #{options[:extended_classes]}"
  end

  def input_class(options={})
    "rounded border border-gray-300 block w-full focus:outline-none focus:border-gray-400 outline-none focus-within:outline-none focus:ring-2 focus:ring-gray-200 #{options[:extended_classes]}"
  end

  def checkbox_class(options={})
    "rounded border-gray-300 border focus:ring-2 focus:ring-gray-200 text-blue-500 mr-1 #{options[:extended_classes]}"
  end

  def link_class(options={})
    "text-gray-700 underline hover:no-underline hover:text-gray-800 block #{options[:extended_classes]}"
  end

  def button_class(options={})
    variant = options[:variant]
    theme = options[:theme]

    style_button(variant, theme_button(theme))
  end

  def theme_button(theme)
    themes = {
      primary: "primary",
      secondary: "secondary",
      transparent: "transparent",
      dark: "dark"
    }

    case theme
    when themes[:primary]
      "bg-indigo-600 hover:bg-indigo-700 text-white"
    when themes[:secondary]
      "bg-teal-600 hover:bg-teal-700 text-white"
    when themes[:transparent]
      "bg-transparent hover:bg-gray-100 text-gray-700"
    when themes[:dark]
      "bg-gray-800 text-white shadow-sm hover:bg-gray-900"
    else
      "bg-white border border-gray-300 shadow-sm hover:bg-gray-100"
    end
  end

  def style_button(variant, theme)
    base = "rounded text-center font-sans font-normal outline-none leading-normal cursor-pointer transition ease-in-out duration-200 font-medium"

    case variant
    when "large"
      "px-5 py-4 text-lg #{base} #{theme}"
    when "small"
      "py-2 px-4 text-sm #{base} #{theme}"
    when "expanded"
      "p-3 w-full block #{base} #{theme}"
    else
      "px-5 py-2 text-base #{base} #{theme}"
    end
  end
end

app/helpers/human_resources_helper.rb
module HumanResourcesHelper
end

app/helpers/marketings_helper.rb
module MarketingsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/helpers/speaking_topics_helper.rb
module SpeakingTopicsHelper
end

app/helpers/sponsor_levels_helper.rb
module SponsorLevelsHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/marketings/_form.html.erb
<%= form_with(model: marketing) do |form| %>
<% if marketing.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(marketing.errors.count, "error") %> prohibited this marketing from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% marketing.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :Content, class: label_class %>
          <%= form.text_field :Content, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Marcom_ID, class: label_class %>
          <%= form.number_field :Marcom_ID, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Content_Name, class: label_class %>
          <%= form.text_area :Content_Name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Description, class: label_class %>
          <%= form.text_area :Description, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :File, class: label_class %>
          <%= form.file_field :File, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Social_Networking_Platform, class: label_class %>
          <%= form.text_field :Social_Networking_Platform, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Person_in_Charge, class: label_class %>
          <%= form.text_area :Person_in_Charge, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Note, class: label_class %>
          <%= form.text_area :Note, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if marketing.persisted? %>
<%= link_to "Cancel", marketing, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", marketings_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/marketings/_marketing.html.erb
<div id="<%= dom_id marketing %>">
  <p>
    <strong>Content:</strong>
    <%= marketing.Content %>
  </p>

  <p>
    <strong>Marcom id:</strong>
    <%= marketing.Marcom_ID %>
  </p>

  <p>
    <strong>Content name:</strong>
    <%= marketing.Content_Name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= marketing.Description %>
  </p>

  <p>
    <strong>File:</strong>
    <%= link_to marketing.File.filename, marketing.File if marketing.File.attached? %>
  </p>

  <p>
    <strong>Social networking platform:</strong>
    <%= marketing.Social_Networking_Platform %>
  </p>

  <p>
    <strong>Person in charge:</strong>
    <%= marketing.Person_in_Charge %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= marketing.Note %>
  </p>

</div>

app/views/marketings/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit marketing</h1>
    <% if @marketing.persisted? %>
    <%= button_to 'Destroy', @marketing, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', marketing: @marketing %>
</div>

app/views/marketings/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Marketings</h1>

    <%= link_to new_marketing_path, class: button_class(theme: "primary") do %>
    Add New Marketing
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Content</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Marcom id</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Content name</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Description</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">File</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Social networking platform</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Person in charge</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Note</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @marketings.each do |marketing| %>
      <%= content_tag :tr, id: dom_id(marketing), class: dom_class(marketing) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= marketing.Content %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= marketing.Marcom_ID %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= marketing.Content_Name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= marketing.Description %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= marketing.File %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= marketing.Social_Networking_Platform %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= marketing.Person_in_Charge %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= marketing.Note %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', marketing %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/marketings/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New marketing</h1>

  <%= render 'form', marketing: @marketing %>
</div>

app/views/marketings/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Marketing</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to marketings_path, class: button_class(theme: "transparent") do %>
      All Marketings
      <% end %>
      <%= link_to edit_marketing_path(@marketing), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Content:</p>
        <p><%= @marketing.Content %></p>
      </li>
      <li>
        <p class="font-semibold">Marcom id:</p>
        <p><%= @marketing.Marcom_ID %></p>
      </li>
      <li>
        <p class="font-semibold">Content name:</p>
        <p><%= @marketing.Content_Name %></p>
      </li>
      <li>
        <p class="font-semibold">Description:</p>
        <p><%= @marketing.Description %></p>
      </li>
      <li>
        <p class="font-semibold">File:</p>
        <p><%= @marketing.File %></p>
      </li>
      <li>
        <p class="font-semibold">Social networking platform:</p>
        <p><%= @marketing.Social_Networking_Platform %></p>
      </li>
      <li>
        <p class="font-semibold">Person in charge:</p>
        <p><%= @marketing.Person_in_Charge %></p>
      </li>
      <li>
        <p class="font-semibold">Note:</p>
        <p><%= @marketing.Note %></p>
      </li>
  </ul>
</div>